### PR TITLE
iOS 10.2 iPhone SE (TSMC and Samsung), iPad Mini 2, iPad Mini 4, iPad Pro 9.7, iPad Pro 12.9, iPad Air, iPad Mini 3 (4,8 and 4,9) Offsets

### PR DESCRIPTION
**Pull request by arinc9**
I need testers for all devices in the title. All offsets are 100% correct. Big thanks to u/OothecaPickle for teaching how to find offsets.

### CODE REVIEW

**Comment by xerub** [comment]
I merged and then reverted. Can you rebase it against master, please? I will merge into cydia myself at given checkpoints.

**Comment by arinc9** [comment]
Did i made it right?

**Comment by xerub** [comment]
Its still in cydia branch. I suggest just porting the relevant changes dex.plist/README.md by hand and making a PR from master. If you think it's too much trouble, I can cherry-pick the commits myself, just let me know. Thanks for the work and sorry for the hassle.

**Comment by xerub** [comment]
Also, patchfinder64 can now output the offsets:
```
clang -o patchfinder64 -DHAVE_MAIN patchfinder64.c
./pf64 <kernel>
```

**Comment by arinc9** [comment]
Ok understood. I'll port dex and readme to master branch. Thanks for your help :)

**Comment by arinc9** [comment]
OK. I opened new pull request and copied my dex.plist and readme.md to Master Branch.

**Pull request merged**
