### PR TITLE
Completely revamp UI

### PR DESCRIPTION
**Pull request by AppleBetas**
Revamps the app's UI.

Video demo: https://www.youtube.com/watch?v=XaVwuku7i1g

Notes:
- I was a bit confused about the jailbreak results, and didn't have a device to test their meanings on, so I have `0` as meaning "jailbroken without any problems" and `42` as "jailbroken but may encounter problems" (I tried to guess from your messages, but may have gotten them wrong)
- The "Enable Substrate" switch is not yet active (because we're on the master branch and I felt this PR would be better suited to go into master), but doing so should be *really* easy

### CODE REVIEW

**Comment by mullak99** [comment]
This looks really nice. Just done some testing on my 7 Plus and it seems to play quite nicely with the Cydia branch too.

Nice work 👍

**Comment by maetrik92** [comment]
Wow awesome! Could you put a toggle also to boot immediately at safe mode?

**Comment by Samgisaninja** [comment]
@maetrik92 thats basically the same as no substrate mode (disabling the substrate switch)

**Comment by mr-f0xx** [comment]
can someone make an ipa of this plz?

**Comment by akikochuchu** [comment]
colud you please  keep ipa.

**Comment by mr-f0xx** [comment]
i don't have a mac :/

**Comment by mullak99** [comment]
I'd recommend creating a macOS VM, it's quite useful :P

Anyway, [here's the version I use](https://builds.mullak99.co.uk/Jailbreak/extra_recipe/custombuilds/extra_recipe+yaluX+AppleBetasUI-v1.0.ipa). The only differences are that I have changed the display name, icon and pulled the cydia branch (so it will install cydia and respring correctly).

**Comment by tekminibi** [comment]
@Mullak99
Video tutorial of what youre talking about?

**Comment by theo78825** [comment]
Is this ever going to be merged??

**Comment by maetrik92** [comment]
Same question

**Comment by mr-f0xx** [comment]
yeah i really want that cool ui :(

**Comment by cuongtovan** [comment]
@mullak99 doesn't it support iPhone 6s, new version of extra_recipe support iPhone 6s added 13 days ago ?, How can I make this UI for that new version

**Comment by mullak99** [comment]
@cuongtovan I've forked xerub's repo and merged Pwn20wnd's and AppleBetas' pull requests, [you can try that if you want](https://github.com/mullak99/extra_recipe/releases).

**Comment by cuongtovan** [comment]
@mullak99 that is what i'm looking for. Thank to you

**Comment by cuongtovan** [comment]
@mullak99 I'm wondering maybe can make this UI for Yalu102 ? :))),I'm have tried with extra_recipe , it's taken so many time to can be success

**Comment by Samgisaninja** [comment]
@cuongtovan now you know how it is to be an iPhone 7 user

**Comment by cuongtovan** [comment]
@Samgisaninja Yeah, That fuckin hard to be jailbroken with extra_recipe

**Comment by AppleBetas** [comment]
An experimental merge of the latest changes has been committed above. If someone with compatible a device could now test it out to make sure I didn't break anything it'd be great.

**Comment by mullak99** [comment]
@AppleBetas You forgot to change both mp variables in offsets.m [(1)](https://github.com/dynasticdevelop/extra_recipe/blob/master/extra_recipe/offsets.m#L143) [(2)](https://github.com/dynasticdevelop/extra_recipe/blob/master/extra_recipe/offsets.m#L154) to include the '.dylib' extension.
[The Error](https://github.com/xerub/extra_recipe/files/1100864/Error.txt)
[Fixed offsets.m](https://github.com/xerub/extra_recipe/files/1100865/offsets.m.txt) (Github doesn't like .M extentions)

**Comment by ghost** [comment]
@AppleBetas says iPad mini 4 isn't supported. Added my custom offsets for 10.1.1, but still not working

**Pull request closed without merging**
